### ISSUE TITLE
Semantic Versioning

### ISSUE THREAD

**Issue by zmillman** [geemus/formatador#20]
Are there plans on using Semantic Versioning for formatador? http://semver.org/

I was updating my version of the fog gem and having a 1.0 release of formatador would have helped make me more confident that upgrading wouldn't introduce any breaking changes

**Comment by geemus** [comment]
This remains valid, and I really should just release v1. If/when I have breaking changes I can always release subsequent majors.

**Comment by geemus** [comment]
Released v1.0.0. Sorry for the enormous delay.
