### ISSUE TITLE
Allow display of a row index

### ISSUE THREAD

**Issue by v0dro** [geemus/formatador#24]
I'm constructing a DataFrame gem for ruby called [daru](https://github.com/v0dro/daru), and it involves row and column indexed data structures.

Currently I've rolled my own version of `#inspect` to display a DataFrame in the console (somewhat) pretty, but if support for single level and hierarchical row indexing could be added to Formatador in the future then that would be fantastic!

**Comment by geemus** [comment]
Hey, thanks for the input. Could you maybe add an example that shows 1) roughly what the data input/call might look like and 2) roughly what the output would look like? I'm just not sure I can picture exactly what you mean otherwise. Thanks!

**Comment by v0dro** [comment]
Sure will upload some pictures in a while.

**Comment by geemus** [comment]
Thanks!
