### ISSUE TITLE
Allow to send color codes even if no tty

### ISSUE THREAD

**Issue by jorgefuertes** [geemus/formatador#31]
Sometimes we need to send the color codes to log files, or stdout is replaced by a logging process like daemontools. Formatador needs an option to force the color codes.

Thanks.

**Comment by jorgefuertes** [comment]
Workaround:

`script -q -c  your_program.rb`

**Comment by geemus** [comment]
Sounds reasonable. I could see having a color option which just defaults to `STDOUT.tty?`, but can be overridden, and then checking that option instead of `tty?` directly in display. Would you be interested in working on a PR for that functionality? Thanks!
