### ISSUE TITLE
Is there a way to right-justify a numeric 

### ISSUE THREAD

**Issue by ytkg** [geemus/formatador#38]
I want to right-justify a numeric.

example:
```ruby
table_data = [
  { :name => "Burger", :price => 200 },
  { :name => "French fries", :price => 120 }
]
Formatador.display_table(table_data)

#=>  +--------------+-------+
#    | name         | price |
#    +--------------+-------+
#    | Burger       |   200 |
#    +--------------+-------+
#    | French fries |   120 |
#    +--------------+-------+
```

**Comment by geemus** [comment]
Great question. Unfortunately there is not currently a direct way to do this.

You can see where it does the current left justification here:

https://github.com/geemus/formatador/blob/master/lib/formatador/table.rb#L67

That being said, as a stop gap you could duplicate that code and move the width of whitespace to precede the datum and end up with right justification. That's probably the easiest way to get to what you wanted. We could think about adding it as an option to the code, but I think things might get a bit complicated rather quickly (and to be honest it's not the easiest code to read and understand as it is pretty deeply into formatting nitty gritty in parts).

Does that make sense?

**Comment by ytkg** [comment]
Yes, it does. Thank you!
I'll give it a try.

**Comment by geemus** [comment]
Sounds good, hope it works well for you!
