### ISSUE TITLE
Building on travis-ci.org is ceased

### ISSUE THREAD

**Issue by ytkg** [geemus/formatador#39]
https://travis-ci.org/github/geemus/formatador
![image](https://user-images.githubusercontent.com/12048864/149941547-e1ea794d-3229-46af-a31e-0ec2225b8ee4.png)

Why not take this opportunity to migrate to GitHub Actions?

**Comment by geemus** [comment]
Yes, thanks for the reminder. I've been trying to slowly but surely migrate my various repositories and hadn't gotten to this one, perhaps particularly because it hasn't really been active in some time.
